// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  accordion: dynamic(() => import('./Accordion')),
  carousel: dynamic(() => import('./Carousel')),
  content: dynamic(() => import('./Content')),
  hero: dynamic(() => import('./Hero')),
  image_with_text: dynamic(() => import('./ImageWithText')),
  newsletter: dynamic(() => import('./Newsletter')),
  steps: dynamic(() => import('./Steps')),
}
